# Configure the Azure provider
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0.2"
    }
  }

  required_version = ">= 1.1.0"
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
  client_id       = var.client_id
  client_secret   = var.client_secret
  tenant_id       = var.tenant_id
}

resource "azurerm_resource_group" "rg" {
  name     = "practica_rg"
  location = var.location

  tags = {
    environment = "CP2"
  }

}
# Storage account
# https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account

resource "azurerm_storage_account" "stAccount" {
  name                     = "storageaccountunir1"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  tags = {
    environment = "CP2"
  }

}

resource "local_file" "tf_ansible_vars_file_new" {
  depends_on = [ azurerm_public_ip.myPublicIp, azurerm_linux_virtual_machine.myVM ]
  content = <<-DOC
    # Ansible hosts containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.
    [all:vars]
    ansible_python_interpreter=/usr/bin/python3
    ansible_user=ansible

    [master]
    master1 ansible_host=${azurerm_public_ip.myPublicIp[0].ip_address}

    [workers]
    worker1 ansible_host=${azurerm_public_ip.myPublicIp[1].ip_address}

    [nfs]
    nfs1 ansible_host=${azurerm_public_ip.myPublicIp[2].ip_address}
    DOC
  filename = "./hosts"
}
