---

## Mostramos Informacion del Cluster
- name: Ejecutando kubectl cluster info
  shell: "kubectl cluster-info"
  register: kubectl_info
  become: yes
  
- name: Mostrando información del Cluster Kubernetes
  debug:
    msg: "{{ kubectl_info.stdout_lines }}"

## Copiando los archivos de despliegue de las aplicaciones al directorio nfs ##
- name: Copiando los archivos de las Aplicaciones
  copy:
    src: "{{ item }}"
    dest: "/nfs/{{ item }}"
    mode: '0644'
  with_items:
    - "{{ files }}"
  become: yes

## Desplegando las Aplicaciones ##
- name: Desplegando las Aplicaciones
  shell: "kubectl apply -f /nfs/{{ item }}"
  register: kubectl_apply_app
  with_items:
    - "{{ files }}"
  become: yes

- name: Mostramos el resultado del despliegue de las Aplicaciones
  debug:
    msg: "{{ item.stdout_lines }}"
  with_items:
    - "{{ kubectl_apply_app.results }}"

- name: URL de la aplicacion
  debug:
    msg: "http://{{ hostvars['master1'].ansible_host }}:30000"
