---

- name: Habilitamos puertos usados por Kubernets Master 6443
  firewalld:
    port: 6443/tcp
    permanent: true
    state: enabled
  become: yes

- name: Habilitamos puertos usados por Kubernets Master 2379-2380 tcp
  firewalld:
    port: 2379-2380/tcp
    permanent: true
    state: enabled
  become: yes

- name: Habilitamos puertos usados por Kubernets Master 10250-10252 tcp
  firewalld:
    port: 10250-10252/tcp
    permanent: true
    state: enabled
  become: yes

- name: Habilitamos puertos usados por Kubernets Master 10255 tcp
  firewalld:
    port: 10255/tcp
    permanent: true
    state: enabled
  become: yes
  
- name: Agregando regla para permitir el acceso de los workers al master
  firewalld:
    rich_rule: "rule family=ipv4 source address={{ hostvars[item].ansible_host }}/32 accept"
    permanent: true
    state: enabled
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.workers }}"
  become: yes


- name: Reiniciando el servicio Firewalld 
  systemd:
    name: firewalld
    state: restarted
  become: yes

- name: Descargando imágenes requeridas por Kubernetes
  shell: kubeadm config images pull
  become: yes
  
    
- name: Instalamos el plugin CNI de kubernetes y definimos la red de los PODs
  shell: "sudo kubeadm init --pod-network-cidr {{ pod_network }}"
  register: kubeadd_cmd
  become: yes

- name: Mostrando la salida de la ejecución del kubeadm init
  debug:
    msg: "{{ kubeadd_cmd.stdout_lines }}"
  

- name: Creamos el directorio .kube
  file:
    path: /root/.kube
    state: directory
  become: yes

- name: Autorizando al usuario root acceder al cluster Kubernetes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
  become: yes

## Instalamos la SDN Flannel ##
- name: Instalamos la SDN Flannel para Azure
  shell: kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml 
  register: kubectl_sdn
  become: yes
  when: sdn == 'flannel'

- name: Mostramos el resultado de la instalación de la SDN Flannel
  debug:
    msg: "{{ kubectl_sdn.stdout_lines }}"
  when: sdn == 'flannel'

- name: Instalamos el operador de Tigera
  shell: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
  register: kubectl_operator
  become: yes
  when: sdn == 'calico'

- name: Copiando el custom resources de Calico
  copy:
    src: custom-resources.yaml
    dest: /root/custom-resources.yaml
    mode: '0644'
  become: yes
  when: sdn == 'calico'
  
- name: Instalamos la SDN Calico
  shell: kubectl apply -f /root/custom-resources.yaml
  register: kubectl_sdn
  become: yes
  when: sdn == 'calico'

- name: Mostramos el resultado de la instalación de la SDN Calico
  debug:
    msg: "{{ kubectl_sdn.stdout_lines }}"
  when: sdn == 'calico'
  
- name: Desplegando el HAProxy Ingress Controller
  shell: kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/master/deploy/haproxy-ingress.yaml
  register: kubectl_haproxy
  become: yes
  
- name: Mostramos el resultado de la instalación del HAProxy Ingress Controller
  debug:
    msg: "{{ kubectl_haproxy.stdout_lines }}"

- name: Extrayendo el comando para hacer el join del worker
  shell: kubeadm token create  --print-join-command
  register: token_out
  become: yes

- name: Limpiando el Token
  set_fact:
   token_hash: "{{ token_out.stdout_lines[0] }}"


- name: Creando el usuario kubeadmin
  user:
    name: kubeadmin
    password: '$6$s3cr3t.s4lt$j3SHtpVd9BgXbQQKpIGiD0nxZdswKkT/mmxmoeTl1I2XQp6Pq.kwfPBErvgOxpOswooWwi6SqmHEmS1T6FxcZ.' ## password='kubeadmin' encriptado
    comment: Usuario administrador de Kubernetes
    create_home: yes
    home: /home/kubeadmin
  become: yes

- name: Creamos el directorio .kube para usuario kubeadmin
  file:
    path: /home/kubeadmin/.kube
    state: directory
  become: yes

- name: Autorizando al usuario kubeadmin acceder al cluster Kubernetes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kubeadmin/.kube/config
    remote_src: yes
    owner: kubeadmin
    group: kubeadmin
  become: yes

- name: Brindando al usuario kubeadmin permisos sudo
  lineinfile:
    dest: /etc/sudoers.d/kubeadmin
    state: present
    create: yes
    line: 'ALL   ALL = (ALL) NOPASSWD: ALL'
  become: yes
